#################ReadMe########################################
#This code will generate the figure seen in figure 3 panel c. The figure is generated by creating an average 
# profile for all early or late replicating domains for each time point in the yeast replication timing experiment.
# This allows us to visualize the average increase and spread of signal over time.
# The input files for this analysis are provided in this directory.
#The input files were generated from the normalized-rebinned-smoothed bedgraphs. Each bedgraph for eachj timepoint was
# joined with a bed file containing a list of erd and lrds regions. The average across all erds or lrds was then calculated and
# compiled into the files used below.


#Load the necessary libraries
library(readr)
library(dplyr)
library(ggplot2)

# Please change this directory to the location of the input files
setwd("/path/to/files")

#Read the input files into the R environment.
df0 <- read_tsv("0min.erd.lrd.averages.traces.txt", col_names = TRUE)
df15 <- read_tsv("15min.erd.lrd.averages.traces.txt", col_names = TRUE)
df20 <- read_tsv("20min.erd.lrd.averages.traces.txt", col_names = TRUE)
df25 <- read_tsv("25min.erd.lrd.averages.traces.txt", col_names = TRUE)
df30 <- read_tsv("30min.erd.lrd.averages.traces.txt", col_names = TRUE)
df35 <- read_tsv("35min.erd.lrd.averages.traces.txt", col_names = TRUE)
df60 <- read_tsv("60min.erd.lrd.averages.traces.txt", col_names = TRUE)
df80 <- read_tsv("80min.erd.lrd.averages.traces.txt", col_names = TRUE)
dfy3cc <- read_tsv("y3cc.erd.lrd.averages.traces.txt", col_names = TRUE)

#Merge the data into one matrix
plotData <- rbind(df0, df15, df20, df25, df30, df35, df60, df80, dfy3cc)

#Split the data into either ERDs or LRDs to plot them separatly.
erd <- filter(plotData, domain=="ERD")
lrd <- filter(plotData, domain=="LRD")

#Make the LRD plots
pLrd<- ggplot(lrd, aes(x = order, y = Value, color = sample, group = sample, linetype = sample))+
  geom_smooth(method = "auto", se = FALSE)+
  scale_color_manual(values = c("0min" = "#00cc00", "15min" = "#00ffaa", "20min"= "#00aaff", "25min"="#0000ff", "30min"="#aa00ff", "35min"="#ff00aa", "60min"="#ff0000", "80min"="#ffaa00", "y3cc"="black"))+
  scale_linetype_manual(values=c("0min" = "solid", "15min" = "solid", "20min"= "solid", "25min"="solid", "30min"="solid", "35min"="solid", "60min"="solid", "80min"="solid", "y3cc"="twodash"))+
  ylim(0, 20)+
  theme(panel.background = element_rect(fill = "white"), 
        legend.background = element_rect(fill = "white"),
        axis.text.x = element_text(size = 0),
        axis.text.y = element_text(size = 12, color = "black"), 
        panel.border = element_rect(color = "black", fill=NA, size=0.5), 
        axis.ticks = element_line(size = 0), 
        legend.key = element_rect(colour = NA, fill = NA))


#Make the ERD plots.
pErd<- ggplot(erd, aes(x = order, y = Value, color = sample, group = sample, linetype = sample))+
  geom_smooth(method = "auto", se = FALSE)+
  scale_color_manual(values = c("0min" = "#00cc00", "15min" = "#00ffaa", "20min"= "#00aaff", "25min"="#0000ff", "30min"="#aa00ff", "35min"="#ff00aa", "60min"="#ff0000", "80min"="#ffaa00", "y3cc"="black"))+
  scale_linetype_manual(values=c("0min" = "solid", "15min" = "solid", "20min"= "solid", "25min"="solid", "30min"="solid", "35min"="solid", "60min"="solid", "80min"="solid", "y3cc"="twodash"))+
  ylim(0, 20)+
  theme(panel.background = element_rect(fill = "white"), 
        legend.background = element_rect(fill = "white"),
        axis.text.x = element_text(size = 0),
        axis.text.y = element_text(size = 12, color = "black"), 
        panel.border = element_rect(color = "black", fill=NA, size=0.5), 
        axis.ticks = element_line(size = 0), 
        legend.key = element_rect(colour = NA, fill = NA))

